[Rainmeter]
Update=1000
Background=#@#\Images\cdframe04.png
BackgroundMode=3
BackgroundMargins=0,10,0,20
W=600
H=337.5

[Variables]
Date=8/15/2026 (00:00:00)
Event=Fifth event
MainTask=Prepare for the fifth event
Step=Build the CMS for the showroom website

;================
;Text styles
;================

[Event]
FontFace=HelveticaNeue
StringAlign=Right
AntiAlias=1
FontColor=219,10,10
FontWeight=900
FontSize=29
;InlineSetting=Stretch | 3 | 0
InlineSetting=CharacterSpacing | -2.0 | 0
X=407
Y=79
Angle=(Rad(1))

[DaysRemaining]
FontFace=FOT-Rodin ProN UB
StringAlign=Center
AntiAlias=1
FontColor=0,0,0
FontWeight=900
FontSize=40
X=460
Y=57
Angle=(Rad(-10))
InlineSetting=CharacterSpacing | -1.25 | -1.25

[DaysRemaining2]
FontFace=FOT-Rodin ProN UB
StringAlign=Center
AntiAlias=1
FontColor=0,0,0
FontWeight=900
FontSize=44
X=437.5
Y=46.5
Angle=(Rad(-10.5))
InlineSetting=CharacterSpacing | 1 | 2

[DaysRemaining3]
FontFace=FOT-Rodin ProN UB
StringAlign=Center
AntiAlias=1
FontColor=0,0,0
FontWeight=900
FontSize=53
X=461.0
Y=44.8
Angle=(Rad(-10.5))
InlineSetting=CharacterSpacing | -2.75 | 2

[Step]
FontFace=Optima nova LT Pro Black
StringAlign=Center
AntiAlias=1
FontColor=255,255,255
FontSize=13
X=296
Y=184.5
InlineSetting=CharacterSpacing | 0.25 | 0

[MainTask]
FontFace=Optima nova LT Pro Black
StringAlign=Center
AntiAlias=1
FontColor=0,0,0
FontSize=19
X=296
Y=130
Angle=(Rad(0.75))
InlineSetting=CharacterSpacing | 0.25 | 0

;============
;Meters
;============

[EventNameMeter]
Meter=String
MeterStyle=Event
Text=#Event#

[Today]
Measure=Time
Format=%m/%d/%Y (%H:%M:%S)

[StaticDate]
Measure=Time
TimeStamp=#Date#
TimeStampFormat=%m/%d/%Y (%H:%M:%S)

[MeasureDaysDifference]
Measure=Calc
Formula=(ABS([StaticDate:] - [Today:Timestamp] + 43200) / 86400)
DynamicVariables=1
RegExpSubstitute=1
Substitute="^(\d)$":"0\1"
IfCondition=MeasureDaysDifference >= 100
IfTrueAction=[!SetOption RemainingMeter MeterStyle "DaysRemaining"][!UpdateMeter *][!Redraw]
IfCondition2=MeasureDaysDifference <= 99
IfTrueAction2=[!SetOption RemainingMeter MeterStyle "DaysRemaining3"][!UpdateMeter *][!Redraw]

[RemainingMeter]
Meter=String
MeasureName=MeasureDaysDifference
MeterStyle=DaysRemaining3
Text=%1

;[MeasureDaysDifference_Tens]
;Measure=Calc
;Formula=Trunc((ABS([StaticDate:] - [Today:Timestamp] + 43200) / 86400) / 100000)
;DynamicVariables=1

;[MeasureDaysDifference_Ones]
;Measure=Calc
;Formula=(ABS([StaticDate:] - [Today:Timestamp] + 43200) / 86400) / ;10000 % (MeasureDaysDifference_Tens * 10)
;DynamicVariables=1

;[RemainingMeter_Tens]
;Meter=String
;MeasureName=MeasureDaysDifference_Tens
;MeterStyle=DaysRemaining2
;Text=%1

;[RemainingMeter_Ones]
;Meter=String
;MeasureName=MeasureDaysDifference_Ones
;MeterStyle=DaysRemaining3
;Text=%1

[MeasureMainTask]
Meter=String
MeterStyle=MainTask
Text=#MainTask#

[MeasureStep]
Meter=String
MeterStyle=Step
Text=#Step#
Angle=(Rad(0.5))

[MeasureMyPictures]
Measure=Plugin
Plugin=QuotePlugin
PathName=#@#\Images
Subfolders=0
FileFilter=*.jpg;*.gif;*.bmp;*.png
UpdateDivider=10